### PR TITLE
Refactor to Auro-Interruption w/ Component Base

### PR DESCRIPTION
**Pull request by gusnaughton**
# Alaska Airlines Pull Request

## Summary:

Refactors dialog into a component-base file for the purpose of adding drawer later.

## Type of change:

Please delete options that are not relevant.

- [x] Revision of an existing capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Comment by gusnaughton** [comment]
@blackfalcon this is ready for your touch. Pending items:

- [ ] have common styles.scss file (I left these separate because I don't know how much you'll touch the drawer styles)

- [ ] Fix the margin issue:
image

I'm aiming to have a similar UI as the CH drawer:
https://components.alaskaair.com/catelog/demo/fs-drawer 

Thanks again Dale!

**Comment by gusnaughton** [comment]
I was able to solve the margin error, but I'm still having trouble fundamentally understanding the left-alignment and centered default nature of this element. Would appreciate pairing on this to learn the cause.

**Comment by gusnaughton** [comment]
@blackfalcon have you had a chance to look at this positioning issue? would love to pair to learn more.

**Comment by blackfalcon** [comment]
@gusnaughton this PR needs to be moved to auro-interruption

**Pull request closed without merging**
